name: CPU PyTest in Conda Work Branch

on:
  push:
    branches:
      - 'work'
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'

jobs:
  build-linux-and-start-pytest:
    runs-on: cpu
    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file tests/workflows_conf/environment_linux_py38.yml --name test -q
      - name: Install Stereopy dependencies
        run: |
          conda init bash
          source ~/.bashrc
          conda activate test

          pip install -r requirements.txt -q
          pip install -r tests/extra_requirements.txt -q
          pip install pathlib -q
          pip install pytest-xdist

          ~/anaconda3/envs/test/bin/python setup.py develop
      - name: Show Env Info
        run: |
          conda init bash
          source ~/.bashrc
          conda activate test
          which python
          conda info
          env
          pip list
      - name: Test with pytest
        run: |
          # TODO ~/anaconda3/envs/test/bin/python -m pytest -m "not gpu and not heavy and not cell_cut_env" --durations=0
          ~/anaconda3/envs/test/bin/python -m pytest -m "not gpu and not heavy and not cell_cut_env" --durations=0

          ~/anaconda3/envs/test/bin/python setup.py develop
      - name: Show Env Info
        run: |
          conda init bash
          source ~/.bashrc
          conda activate test
          which python
          conda info
          env
          pip list
      - name: Test with pytest
        run: |
          # TODO ~/anaconda3/envs/test/bin/python -m pytest -m "not gpu and not heavy and not cell_cut_env" --durations=0
          ~/anaconda3/envs/test/bin/python -m pytest -m "not gpu and not heavy and not cell_cut_env" --durations=0
