name: CPU PyTest Demo in Conda Tanliwei Branch

on:
  push:
    branches:
      - 'tanliwei'
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'

jobs:
  build-linux-and-start-pytest:
    runs-on: cpu
    defaults:
      run:
        shell: bash
    steps:
    #   - uses: actions/checkout@v3
      - name: Activate Conda Enviroment
        run: |
          echo "using conda $(which conda)"
          conda activate test

          echo "using python $(which python)"