name: CPU PyTest in Conda

on:
  push:
    branches:
      - 'lyonlin'
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'

jobs:
  build-linux-and-start-pytest:
    runs-on: cpu
    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file tests/workflows_conf/environment_linux_py38.yml --name test_requirement -q
      - name: Install Stereopy dependencies
        run: |
          conda init bash
          source ~/.bashrc
          conda activate test_requirement

          pip install -r requirements.txt -q
          # TODO temporarily not install `tests/extra_requirements.txt`
          # pip install -r tests/extra_requirements.txt -q
          pip install pathlib -q
          pip install pytest-xdist

          ~/anaconda3/envs/test_requirement/bin/python setup.py develop
      - name: Show Env Info
        run: |
          conda init bash
          source ~/.bashrc
          conda activate test_requirement
          which python
          conda info
          env
          pip list
      - name: Test with pytest
        run: |
          ~/anaconda3/envs/test_requirement/bin/python -m pytest -m "not gpu and not heavy" --durations=0
      - name: Remove conda env
        run: |
          conda init bash
          source ~/.bashrc
          conda env remove -n test_requirement